CREATE TABLE IF NOT EXISTS RSS(
    FEED_ID INTEGER NOT NULL,
    CREATED DATE,
    TITLE TEXT NOT NULL,
    LINK TEXT NOT NULL,
    PUBLISHED DATE,
    AUTHOR TEXT,
        FOREIGN KEY (FEED_ID) REFERENCES FEED(ID)
);